# Generated by Django 4.1.5 on 2023-01-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_column='company_name', max_length=256)),
                ('country', models.CharField(db_column='country', max_length=256)),
                ('city', models.CharField(db_column='city ', max_length=256)),
                ('address', models.CharField(db_column='address', max_length=256)),
                ('phone_num', models.IntegerField(db_column='phone_num')),
            ],
            options={
                'db_table': 'companys',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first name', max_length=256)),
                ('last_name', models.CharField(db_column='last name', max_length=256)),
                ('personal_email', models.CharField(db_column='Email', max_length=256)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Polygender', 'P'), ('Genderfluid', 'G'), ('Agender', 'A'), ('Bigender', 'B')], db_column='gender ', max_length=256)),
                ('birth_date', models.DateField(db_column='date', default='1900-01-01')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_column='job title', max_length=256)),
                ('is_current_job', models.BooleanField(null=True)),
                ('company_email', models.CharField(db_column='Email', max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_places.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_places.person')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='persons',
            field=models.ManyToManyField(through='work_places.Employee', to='work_places.person'),
        ),
    ]
