# Generated by Django 4.1.5 on 2023-01-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_num',
            field=models.CharField(db_column='phone_num', max_length=256),
        ),
    ]
