# Generated by Django 4.1.5 on 2023-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_places', '0002_alter_company_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(db_column='date', max_length=256),
        ),
    ]
