# Generated by Django 4.1.5 on 2023-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_places', '0003_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_current_job',
            field=models.CharField(db_column='is_current_job', max_length=256),
        ),
    ]
