# Generated by Django 4.1.5 on 2023-01-30 15:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_places', '0004_alter_employee_is_current_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(db_column='birth_date', validators=[django.core.validators.MinValueValidator(datetime.datetime(1900, 1, 1, 0, 0)), django.core.validators.MaxValueValidator(datetime.datetime.now)]),
        ),
    ]
